language: java

matrix:
  include:
    - jdk: openjdk8
      env: TARGET=checkstyle
    - jdk: openjdk8
      env: TARGET=pmd
    - jdk: openjdk8
      env: TARGET=cpd
    - jdk: openjdk8
      env: TARGET=test
      services: xvfb
    - jdk: openjdk11
      env: TARGET=test
      services: xvfb
    - os: osx
      osx_image: xcode11.3 # Java 14, macOS 10.14.6 (last with 32-bit support)
      env: TARGET=test
    - os: windows
      env: TARGET=test

addons:
  apt:
    packages: clasp
  homebrew:
    packages: clasp

install:
  - ./gradlew assemble

script:
  - ./gradlew $TARGET
  - if [ $TARGET = test ]; then ./ci/run.sh; fi

after_success:
  - if [ $TARGET = test -a $TRAVIS_JDK_VERSION = openjdk8 ]; then ./gradlew coveralls; fi
